### ISSUE TITLE
Does this app runs with GPU support?

### ISSUE THREAD

**Issue by hdnh2006** [AneeqMalik/flutter_pytorch#1]
Hello, thanks for sharing this code.

I would like to know if this app runs the models with GPU support. As you already know, PyTorch doesn't have support for Mobile GPU, I mean it is in beta version from a couple of years ago and it seems it won't change.

PyTorch already publish an app that uses yolov5 with just CPU support which is good but slow in real time inference (https://github.com/pytorch/android-demo-app/tree/master/ObjectDetection).

So, my question is, does your app runs with GPU mobile support?

Thanks in advance.

**Comment by AneeqMalik** [comment]
> 


PyTorch on Mobile GPUs


Aneeq Fayyaz Karim Malik
Hello, thanks for sharing this code.

I would like to know if this app runs the models with GPU support. As you already know, PyTorch doesn't have support for Mobile GPU, I mean it is in beta version from a couple of years ago and it seems it won't change.

PyTorch already publish an app that uses yolov5 with just CPU support which is good but slow in real time inference (https://github.com/pytorch/android-demo-app/tree/master/ObjectDetection).

So, my question is, does your app runs with GPU mobile support?

Thanks in advance.
Write a reply to the above message saying no as Pytorch models doesnot have native support for that you have to convert your model to other format like tflite to achieve GPU support for mobiles

Hello! Unfortunately, PyTorch models do not have native support for running on GPUs in mobile devices. As you mentioned, PyTorch has a beta version for mobile GPUs, but it seems that this feature will not be fully developed. To achieve GPU support on mobile devices, you may need to convert your PyTorch model to another format, such as TensorFlow Lite (TFLite), which is designed for running on mobile devices with GPU acceleration.

Converting your model to TFLite can be done using the TensorFlow Lite converter, which can convert models from various formats, including PyTorch, to TFLite. After the conversion, you can use the TFLite interpreter to run your model on mobile devices with GPU support. Keep in mind that the conversion process may require some adjustments to ensure that the converted model performs well on the target device.

I hope this helps! Let me know if you have any further questions.

**Comment by AneeqMalik** [comment]
@hdnh2006 
Hello! Unfortunately, PyTorch models do not have native support for running on GPUs in mobile devices. As you mentioned, PyTorch has a beta version for mobile GPUs, but it seems that this feature will not be fully developed. To achieve GPU support on mobile devices, you may need to convert your PyTorch model to another format, such as TensorFlow Lite (TFLite), which is designed for running on mobile devices with GPU acceleration.

Converting your model to TFLite can be done using the TensorFlow Lite converter, which can convert models from various formats, including PyTorch, to TFLite. After the conversion, you can use the TFLite interpreter to run your model on mobile devices with GPU support. Keep in mind that the conversion process may require some adjustments to ensure that the converted model performs well on the target device.

I hope this helps! Let me know if you have any further questions.
