### ISSUE TITLE
Drawing bounding boxes on image

### ISSUE THREAD

**Issue by smfaizanahmed** [AneeqMalik/flutter_pytorch#9]
The function renderBoxes work perfectly well for displaying the rendered boxes but I want to save the rendered image in device. Is there any function available ?

**Comment by AneeqMalik** [comment]
@smfaizanahmed No there isn't for the time being. However for this similar requirement I used a screen shot capture package to catch the current areas of the detection and save as an image on the device.

**Comment by AneeqMalik** [comment]
@smfaizanahmed No there isn't for the time being. However for this similar requirement I used a screen shot capture package to catch the current areas of the detection and save as an image on the device.
